development:
  adapter: redis
  url: redis://localhost:6379
  channel_prefix: varland_apps_development

test:
  adapter: test

production:
  adapter: redis
  url: redis://apps.varland.com:6379
  channel_prefix: varland_apps_production
