default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= Rails.application.credentials.dev_db[:host] %>
  username: <%= Rails.application.credentials.dev_db[:user] %>
  password: <%= Rails.application.credentials.dev_db[:password] %>
  database: <%= Rails.application.credentials.dev_db[:database] %>

test:
  <<: *default
  host: <%= Rails.application.credentials.test_db[:host] %>
  username: <%= Rails.application.credentials.test_db[:user] %>
  password: <%= Rails.application.credentials.test_db[:password] %>
  database: <%= Rails.application.credentials.test_db[:database] %>

production:
  <<: *default
  host: <%= Rails.application.credentials.prod_db[:host] %>
  username: <%= Rails.application.credentials.prod_db[:user] %>
  password: <%= Rails.application.credentials.prod_db[:password] %>
  database: <%= Rails.application.credentials.prod_db[:database] %>