---
:concurrency: 1

:queues:
  - default
  - mailers

:schedule:
  UpdateUsersJob:
    cron: '0 */5 * * * *'
    queue: default
    enabled: true
  Groov::ReclassifyLogsJob:
    cron: '0 */5 * * * *'
    queue: default
    enabled: true