---
:concurrency: 1

:queues:
  - default
  - mailers

:schedule:
  UpdateUsersJob:
    cron: '0 0 * * * *'
    queue: default
    enabled: true
  ReclassifyGroovLogsJob:
    cron: '0 0 * * * *'
    queue: default
    enabled: true